# override usegalaxy.org.au domain by appending gvl.org.au to ansible_hostname (from hosts file) for hostname variable
hostname: "{{ ansible_hostname }}.gvl.org.au"

galaxy_uid: 998

galaxy_gid: 998

#Monitoring for Staging. Once all VM monitoring has moved to stats.usegalaxy.org.au, this can be put in all.yml and removed here.
influx_url: stats.usegalaxy.org.au
grafana_server_url: "https://{{ influx_url }}:8086"

telegraf_agent_output:
  - type: influxdb
    config:
    - urls = ["{{ grafana_server_url }}"]
    - database = "dev"
    - username = "node"
    - password = "{{ vault_influx_node_password }}"

# dbservers and galaxyservers
galaxy_db_user_password: "{{ vault_dev_db_user_password }}"
galaxy_db_reader_password: "{{ vault_dev_db_reader_password }}"
galaxy_db_tiaasadmin_password: "{{ vault_dev_db_tiaasadmin_password }}"
galaxy_db_tiaas_password: "{{ vault_dev_db_tiaas_password }}"

install_python_311: True

# Override permission level for tool devs on dev
host_machine_users:
    - name: mike
      uid: 7201
      roles:
        - sudo
        - galaxy_admin
      key: files/keys/mike.pub
      email: "{{ mike_email }}"
    - name: tom
      uid: 7203
      roles:
        - sudo
        - galaxy_admin
      key: files/keys/tom.pub
      email: "{{ tom_email }}"
    - name: jonathan
      uid: 7401
      roles: []
      key: files/keys/jonathan.pub
      email: "{{ jonathan_email }}"
