#Slurm roles
slurm_roles: ['controller', 'exec', 'dbd']

#Mariadb for slurm accounting
mariadb_password_root: "{{ vault_mariadb_password_root }}"
mariadb_password_slurm: "{{ vault_mariadb_password_slurm }}"

#NFS shares

nfs_exports:
    - "{{ pulsar_custom_indices_dir }}  *(rw,async,no_root_squash,no_subtree_check)"
    - "/mnt/pulsar  *(rw,async,no_root_squash,no_subtree_check)"

# Pulsar
pulsar_package_name: git+https://github.com/galaxyproject/pulsar
pulsar_package_version: 973f7b3

pulsar_root: /mnt/pulsar
pulsar_server_dir: /mnt/pulsar/server
pulsar_venv_dir: /mnt/pulsar/venv
pulsar_config_dir: /mnt/pulsar/config
pulsar_staging_dir: /mnt/pulsar/files/staging
pulsar_persistence_dir: /mnt/pulsar/files/persistent_data
pulsar_dependencies_dir: /mnt/pulsar/deps

pulsar_pip_install: true
pulsar_pycurl_ssl_library: openssl
pulsar_systemd: true
pulsar_systemd_runner: webless

pulsar_user:
  name: ubuntu
  shell: /bin/bash

pulsar_ssl_pem: /etc/ssl/certs/host.pem

pulsar_optional_dependencies:
  - pyOpenSSL
  - psutil
  - pycurl<=7.45.2
  - drmaa
  - kombu>=5.2.0
  - sentry-sdk

install_drmaa: true
pulsar_drmaa_library_path: /usr/lib/slurm-drmaa/lib/libdrmaa.so.1

pulsar_yaml_config:
  managers:
      _default_:
          type: queued_drmaa
          preprocess_action_max_retries: 50
          preprocess_action_interval_start: 2
          preprocess_action_interval_step: 2
          preprocess_action_interval_max: 60
          postprocess_action_max_retries: 18
          postprocess_action_interval_start: 2
          postprocess_action_interval_step: 2
          postprocess_action_interval_max: 120
          min_polling_interval: 15
  dependency_resolution:
    resolvers:
      - type: conda
        exec: "{{ pulsar_conda_prefix }}/bin/{{ pulsar_conda_exec|d('conda') }}"
        auto_init: true
        auto_install: true
        prefix: "{{ pulsar_conda_prefix }}"
      - type: conda
        exec: "{{ pulsar_conda_prefix }}/bin/{{ pulsar_conda_exec|d('conda') }}"
        auto_init: true
        auto_install: true
        prefix: "{{ pulsar_conda_prefix }}"
        versionless: true
  staging_directory: "{{ pulsar_staging_dir }}"
  persistence_directory: "{{ pulsar_persistence_dir }}"
  message_queue_url: "pyamqp://{{ pulsar_rabbit_username }}:{{ rabbitmq_password_galaxy_au }}@{{ pulsar_queue_url }}:5671/{{ pulsar_rabbit_vhost }}?ssl=1"
  min_polling_interval: 0.5
  amqp_publish_retry: True
  amqp_publish_retry_max_retries: 5
  amqp_publish_retry_interval_start: 10
  amqp_publish_retry_interval_step: 10
  amqp_publish_retry_interval_max: 60
  sentry_dsn: "{{ vault_sentry_url_pulsar_production if ansible_hostname in groups['production_pulsars'] else None }}"
  maximum_stream_size: 8388608

pulsar_conda_prefix: "{{ pulsar_dependencies_dir }}/_conda"
miniconda_prefix: "{{ pulsar_conda_prefix }}"

pulsar_singularity_cachedir: "{{ pulsar_dependencies_dir }}/singularity"
pulsar_singularity_tmpdir: "{{ pulsar_singularity_cachedir }}/tmp"

# for pulsar-post-tasks
pulsar_custom_indices_dir: /mnt/custom-indices

#Stats collection
add_utilisation_info: true
stats_dir: /home/ubuntu/stats_collection

# docker
docker_users:
  - "{{ pulsar_user.name }}"

# acl-on-startup role
acl_job_runner_user: "{{ pulsar_user.name }}"
