- hosts: dev_handlers_server
  become: true
  vars_files:
    - group_vars/all.yml
    - group_vars/dev.yml # machine_users overridden in this file
    - group_vars/VAULT
    - group_vars/galaxyservers.yml
    - group_vars/dev_slurm.yml
    - host_vars/dev.gvl.org.au.yml
    - host_vars/dev-handlers.gvl.org.au.yml
    - secret_group_vars/ssh_keys
    - secret_group_vars/stats_server_vault
    - secret_group_vars/dev_secrets
    - secret_group_vars/sentry_vault
  pre_tasks:
    - name: Run common role first to create galaxy user
      include_role:
        name: common
    - name: create dir for gravity configuration
      file:
        state: directory
        path: /opt/galaxy
        owner: root
        group: galaxy
        mode: 0775
    - name: create dir for galaxy's singularity cache # this is still on the root disk, it's a test of moving the singularity cache
      file:
        state: directory
        path: "{{ item }}"
        owner: galaxy
        group: galaxy
        mode: 0700
      with_items:
        - "{{ galaxy_user_singularity_cachedir }}"
        - "{{ galaxy_user_singularity_tmpdir }}"
  roles:
    - galaxyproject.repos
    - insspb.hostname
    - mounts
    - geerlingguy.pip
    - galaxyproject.galaxy
    # - role: galaxyproject.miniconda  # maybe this is never needed from the handlers playbook, will see
    #   become: true
    #   become_user: galaxy
    - nginx-upload-module
    - galaxyproject.nginx
    - galaxyproject.tusd
    - galaxyproject.slurm
    - galaxyproject.cvmfs
    - galaxyproject.gxadmin
    - postfix-mail-relay
    - geerlingguy.docker
    - usegalaxy_eu.apptainer
    - dj-wasabi.telegraf
    - usegalaxy_eu.flower
    - acl-on-startup
  post_tasks:
    - name: Make local_tool directory group-writable by machine users
      file:
        path: /mnt/galaxy/local_tools
        owner: root
        group: devs
        mode: 0775
        state: directory
    - name: Install slurm-drmaa
      package:
        name: slurm-drmaa1

