- hosts: dev-pulsar
  become: true
  vars_files:
    - group_vars/all.yml
    - group_vars/dev.yml
    - group_vars/pulsarservers.yml
    - group_vars/dev_pulsar_slurm.yml
    - group_vars/VAULT
    - host_vars/dev-pulsar.gvl.org.au.yml
    - secret_group_vars/ssh_keys
    - secret_group_vars/stats_server_vault
  pre_tasks:
    - name: Create pulsar deps path
      file:
        path: "{{ pulsar_dependencies_dir }}"
        state: directory
        owner: "{{ pulsar_user.name }}"
        group: "{{ pulsar_user.name }}"
  roles:
    - common
    - geerlingguy.pip
    - galaxyproject.repos
    - role: galaxyproject.miniconda
      become: true
      become_user: "{{ pulsar_user.name }}"
    - galaxyproject.pulsar
    - geerlingguy.nfs
    - mariadb
    - galaxyproject.slurm
    - galaxyproject.cvmfs
    - usegalaxy_eu.apptainer
    - geerlingguy.docker
    - acl-on-startup
    - dj-wasabi.telegraf
    - pulsar-post-tasks
    - slurm-post-tasks
