- hosts: galaxy_workers
  become: true
  vars_files:
      - group_vars/all.yml
      - group_vars/galaxy_etca.yml
      - group_vars/VAULT
      - group_vars/galaxy_etca_slurm.yml
      - group_vars/galaxy_workers.yml
      - secret_group_vars/ssh_keys  # TODO: when branches are merged, rename this file to internal_keys
      - secret_group_vars/stats_server_vault
  pre_tasks:
      - name: Attach volume to instance
        include_role:
          name: attached-volumes
      - name: Create containing folders for external NFS file mounts
        file:
          state: directory
          path: "{{ item }}"
        with_items:
          - "{{ qld_file_mounts_path }}"

      # the following is a workaround for dj-wasabi.telegraf role breaking on new VMs
      # the issue is that the dj-wasabi.telegraf role is not dearmoring the downloaded key
      # the dearmored key location is then passed to dj-wasabi.telegraf via a variable
      - name: Ensure /etc/apt/keyrings exists
        ansible.builtin.file:
          path: /etc/apt/keyrings
          state: directory
          mode: "0755"
        become: true

      - name: Fetch InfluxData key (ascii)
        ansible.builtin.get_url:
          url: https://repos.influxdata.com/influxdata-archive.key
          dest: /etc/apt/keyrings/influxdata-archive.asc
          mode: "0644"
        register: influx_key
        until: influx_key is succeeded
        retries: 3
        delay: 2
        become: true

      - name: Dearmor into a binary keyring if key has changed
        ansible.builtin.command: >
          gpg --batch --yes --dearmor
          -o /etc/apt/keyrings/influxdata-archive.gpg
          /etc/apt/keyrings/influxdata-archive.asc
        when: influx_key.changed
        become: true

      - name: Ensure permissions on keyring
        ansible.builtin.file:
          path: /etc/apt/keyrings/influxdata-archive.gpg
          owner: root
          group: root
          mode: "0644"
        become: true

  roles:
      - common
      - geerlingguy.pip
      - mounts
      - galaxyproject.repos
      - galaxyproject.slurm
      - galaxyproject.cvmfs
      - role: dj-wasabi.telegraf
        vars:
          # override the role’s internal set_fact when create telegraf.list
          telegraf_repository_params: "[signed-by=/etc/apt/keyrings/influxdata-archive.gpg]"
      - usegalaxy_eu.apptainer
      - geerlingguy.docker
      - acl-on-startup
      - clean-tmpdisk
  post_tasks:
      - name: restart munge
        systemd:
            name: munge
            state: restarted
      - name: Move /tmp to vdc # TODO: Factor this out to its own role, it is copied/pasted in about 10 playbooks
        block:
          - name: Create worker tmpdir on vdc
            file:
                path: /mnt/tmpdisk
                state: directory
                owner: root
                group: root
                mode: '1777'
          - name: stat links
            stat:
                path: /tmp
            register: links
          - name: remove old tmp
            file:
                path: /tmp
                state: absent
            when: links.stat.islnk is defined and not links.stat.islnk
          - name: Link /tmp to /mnt/tmpdisk
            file:
                src: /mnt/tmpdisk
                dest: /tmp
                state: link
            become: yes
            become_user: root
            when: links.stat.islnk is defined and not links.stat.islnk
        when: attached_volumes is defined

