---
# Deploy the Galaxy Media Site
- hosts: gms_webservers
  remote_user: ubuntu
  become: true
  vars_files:
    - group_vars/VAULT
    - group_vars/gms.yml
    - host_vars/dev-site.gvl.org.au.yml
  pre_tasks:
    - name: Grant USAGE and CREATE privileges on public schema to the user
      shell: >
        sudo -u postgres psql -d {{ postgres_db_name }} -c "GRANT USAGE, CREATE ON SCHEMA public TO {{ postgres_db_user }};"
  roles:
    - role: geerlingguy.nginx
      tags: init
    - role: geerlingguy.postgresql
      become: true
      tags: init,postgresql
    - role: galaxy_media_site
      tags: gms
