---
- hosts: labs_engine_dev
  remote_user: ubuntu
  become: true
  vars_files:
    - group_vars/all.yml
    - group_vars/VAULT
    - secret_group_vars/ssh_keys
    - secret_group_vars/labs_engine_vault
    - group_vars/labs_engine.yml
    - host_vars/dev-labs.gvl.org.au.yml
  post_tasks:
    - name: Add GitHub SI pub key to authorized_keys
      authorized_key:
        user: ubuntu
        key: "{{ lookup('file', 'keys/gms-labs-ci.pub') }}"
  roles:
    - role: common
      become: true
      become_user: root
    - insspb.hostname
    - dj-wasabi.telegraf
    - role: geerlingguy.docker
      tags: init
    - role: galaxy_labs_engine
      tags: always
