- hosts: nci-build
  become: true
  vars_files:
      - group_vars/all.yml
      - group_vars/VAULT
      - secret_group_vars/ssh_keys
  vars:
    - build_machines_ansible_version: '5.6.0'
    - build_machines_ansible_venv: /home/ubuntu/venv
  roles:
    - common
    - geerlingguy.pip
    - dj-wasabi.telegraf
  post_tasks:
    - name: Ensure desired version of ansible is installed
      pip:
        name: "ansible=={{ build_machines_ansible_version }}"
        umask: "0022"
        virtualenv: "{{ build_machines_ansible_venv }}"
    - name: Clone infrastructure repo
      git:
        repo: https://github.com/usegalaxy-au/infrastructure
        dest: /home/ubuntu/infrastructure
        update: yes
      become: yes
      become_user: ubuntu
    - name: Update ansible roles
      command:
        cmd: "{{ build_machines_ansible_venv }}/bin/ansible-galaxy install -p roles -r requirements.yml"
        chdir: /home/ubuntu/infrastructure
      become: yes
      become_user: ubuntu
    - name: add galaxy australia authorised key
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', 'files/keys/galaxy-australia.pub') }}"
    - name: Add venv activation to ubuntu's .bashrc
      lineinfile:
        path: /home/ubuntu/.bashrc
        line: ". {{ galaxy_backup_ansible_venv }}/bin/activate"

  