- name: Pulsar QLD worker node install
  hosts: pulsar_QLD_workers
  become: yes
  vars_files:
    - group_vars/all.yml
    - group_vars/pulsarservers.yml
    - group_vars/pulsar_QLD/pulsar-QLD.yml
    - group_vars/pulsar_QLD/pulsar-QLD_workers.yml
    - group_vars/pulsar_QLD/pulsar-QLD_slurm.yml
    - group_vars/VAULT
    - secret_group_vars/stats_server_vault
  pre_tasks:
    - name: Attach volume to instance
      include_role:
        name: attached-volumes
  roles:
      - common
      - galaxyproject.slurm
      - mounts
      - galaxyproject.repos
      - galaxyproject.cvmfs
      - usegalaxy_eu.apptainer
      - geerlingguy.docker
      - acl-on-startup
      - dj-wasabi.telegraf
      - tmp-relocation
      - clean-tmpdisk
  post_tasks:
    - name: Restart munge service
      service:
          name: munge
          state: restarted
    - name: Reload cvmfs config
      command:
        cmd: cvmfs_config reload
      become: yes
    - name: Run disable-cgroups-v2 role
      include_role:
        name: disable-cgroups-v2
