- name: Pulsar NCI Test worker node install
  hosts: pulsar_nci_test_workers
  become: yes
  vars_files:
    - group_vars/all.yml
    - group_vars/pulsarservers.yml
    - group_vars/pulsar-nci-test/pulsar-nci-test.yml
    - group_vars/pulsar-nci-test/pulsar-nci-test_workers.yml
    - group_vars/pulsar-nci-test/pulsar-nci-test_slurm.yml
    - group_vars/VAULT
    - secret_group_vars/ssh_keys
  pre_tasks:
    # NCI machines have a /mnt entry already in fstab. Due to legacy crud we really
    # need to mount the volume at /mnt
    - name: Comment out the /dev/vdb mount at /mnt
      replace:
        path: /etc/fstab
        regexp: '^(\s*)/dev/vdb(\s+/mnt\s+)'
        replace: '\1# /dev/vdb\2'
    - name: Attach volume to instance
      include_role:
        name: attached-volumes
  roles:
      - common
      - galaxyproject.slurm
      - mounts
      - galaxyproject.repos
      - galaxyproject.cvmfs
      - usegalaxy_eu.apptainer
      - geerlingguy.docker
      - acl-on-startup
      - dj-wasabi.telegraf
      - tmp-relocation
      - clean-tmpdisk
      - disable-cgroups-v2
