- hosts: pulsar_qld_blast
  become: true
  vars_files:
    - group_vars/all.yml
    - group_vars/pulsarservers.yml
    - host_vars/pulsar-qld-blast.yml
    - group_vars/VAULT
    - secret_group_vars/stats_server_vault
    - secret_group_vars/ssh_keys
  roles:
    - common
    - geerlingguy.pip
    - galaxyproject.repos
    - pulsar-pre-tasks
    - role: galaxyproject.miniconda
      become: true
      become_user: "{{ pulsar_user.name }}"
    - galaxyproject.pulsar
    - mariadb
    - galaxyproject.slurm
    - galaxyproject.cvmfs
    - usegalaxy_eu.apptainer
    - geerlingguy.docker
    - acl-on-startup
    - dj-wasabi.telegraf
    - pulsar-post-tasks
    - slurm-post-tasks
    - slg.galaxy_stats
    - tmp-relocation
    - disable-cgroups-v2
