- name: Pulsar NCI Training Head Node
  hosts: pulsar_nci_training_head
  become: true
  pre_tasks:
    # NCI machines have a /mnt entry already in fstab. Due to legacy crud we really
    # need to mount the volume at /mnt
    - name: Comment out the /dev/vdb mount at /mnt
      replace:
        path: /etc/fstab
        regexp: '^(\s*)/dev/vdb(\s+/mnt\s+)'
        replace: '\1# /dev/vdb\2'
    - name: Attach volume to instance
      include_role:
        name: attached-volumes
  vars_files:
    - group_vars/all.yml
    - group_vars/pulsar_nci_training/pulsar-nci-training.yml
    - group_vars/pulsarservers.yml
    - group_vars/pulsar_nci_training/pulsar-nci-training_slurm.yml
    - group_vars/VAULT
    - host_vars/pulsar-nci-training/pulsar-nci-training.usegalaxy.org.au.yml
    - secret_group_vars/stats_server_vault
    - secret_group_vars/ssh_keys
  roles:
    - common
    - insspb.hostname
    - geerlingguy.pip
    - galaxyproject.repos
    - pulsar-pre-tasks
    - role: galaxyproject.miniconda
      become: true
      become_user: "{{ pulsar_user.name }}"
    - galaxyproject.pulsar
    - geerlingguy.nfs
    - mariadb
    - galaxyproject.slurm
    - galaxyproject.cvmfs
    - usegalaxy_eu.apptainer
    - geerlingguy.docker
    - acl-on-startup
    - dj-wasabi.telegraf
    - pulsar-post-tasks
    - slurm-post-tasks
    - slg.galaxy_stats
    - disable-cgroups-v2
