- hosts: pulsar_qld_himems
  become: true
  vars_files:
    - group_vars/all.yml
    - group_vars/pulsarservers.yml
    - group_vars/VAULT
    - secret_group_vars/stats_server_vault
    - secret_group_vars/ssh_keys
  pre_tasks:
    - name: Attach volume to instance
      include_role:
        name: attached-volumes
  roles:
    - common
    - geerlingguy.pip
    - galaxyproject.repos
    - pulsar-pre-tasks
    - role: galaxyproject.miniconda
      become: true
      become_user: "{{ pulsar_user.name }}"
    - galaxyproject.pulsar
    - mariadb
    - galaxyproject.slurm
    - galaxyproject.cvmfs
    - usegalaxy_eu.apptainer
    - geerlingguy.docker
    - acl-on-startup
    - dj-wasabi.telegraf
    - pulsar-post-tasks
    - slurm-post-tasks
    - slg.galaxy_stats
    - tmp-relocation
    - clean-tmpdisk
  post_tasks:
    - name: Update max_map_count to 1,000,000 for maxquant
      command:
        cmd: sysctl -w vm.max_map_count=1000000
    - name: limit processes spawned by slurm jobs on qld-pulsar-himem-2
      #  limit number of slurm cgroup processes to prevent mothur forking to infinity
      lineinfile:
          path: /lib/systemd/system/slurmd.service
          regexp: "^TasksMax="
          line: "TasksMax=5000"
      when: inventory_hostname.endswith('high-mem2')
    - name: reload systemd manager configuration for changes to take effect
      systemd:
          state: restarted
          daemon_reload: yes
          name: slurmd
      when: inventory_hostname.endswith('high-mem2')
    - name: Create ncbi_fcs_gx data folder
      file:
        path: /mnt/ncbi_fcs_gx_db
        state: directory
        owner: "{{ pulsar_user.name }}"
        group: "{{ pulsar_user.name }}"
      when: inventory_hostname.endswith('high-mem2')
    - name: Run update cgroups task last
      include_role:
        name: disable-cgroups-v2
