- name: Pulsar NCI training worker node install
  hosts: pulsar_nci_training_workers
  become: yes
  vars_files:
    - group_vars/all.yml
    - group_vars/pulsarservers.yml
    - group_vars/pulsar_nci_training/pulsar-nci-training.yml
    - group_vars/pulsar_nci_training/pulsar-nci-training_workers.yml
    - group_vars/pulsar_nci_training/pulsar-nci-training_slurm.yml
    - group_vars/VAULT
    - secret_group_vars/stats_server_vault
    - secret_group_vars/ssh_keys
  pre_tasks:
    # - name: Remove cloudinit entry in fstab
    #   # remove line '/dev/vdb	/mnt	auto	defaults,nofail,x-systemd.requires=cloud-init.service,comment=cloudconfig	0	2'
    #   # because this is the same mount point as the one we need for the attached volume + pulsar nfs mount
    #   lineinfile:
    #     path: /etc/fstab
    #     regexp: "\/dev\/vdb\\s+\/mnt.*"
    #     state: absent
    - name: Attach volume to instance
      include_role:
        name: attached-volumes
  roles:
      - common
      - insspb.hostname
      - galaxyproject.slurm
      - mounts
      - galaxyproject.repos
      - galaxyproject.cvmfs
      - usegalaxy_eu.apptainer
      - geerlingguy.docker
      - acl-on-startup
      - dj-wasabi.telegraf
      - tmp-relocation
      - clean-tmpdisk
      - disable-cgroups-v2

