- hosts: pulsar-mel3
  become: true
  vars_files:
    - group_vars/all.yml
    - group_vars/pulsar_mel3/pulsar-mel3.yml
    - group_vars/pulsarservers.yml
    - group_vars/pulsar_mel3/pulsar-mel3_slurm.yml
    - group_vars/VAULT
    - host_vars/pulsar-mel3/pulsar-mel3.genome.edu.au.yml
    - secret_group_vars/stats_server_vault
    - secret_group_vars/ssh_keys
  pre_tasks:
    - name: Attach volume to instance
      include_role:
        name: attached-volumes
  roles:
    - common
    - geerlingguy.pip
    - galaxyproject.repos
    - pulsar-pre-tasks
    - role: galaxyproject.miniconda
      become: true
      become_user: "{{ pulsar_user.name }}"
    - galaxyproject.pulsar
    - geerlingguy.nfs
    - mariadb
    - galaxyproject.slurm
    - galaxyproject.cvmfs
    - usegalaxy_eu.apptainer
    - geerlingguy.docker
    - acl-on-startup
    - dj-wasabi.telegraf
    - pulsar-post-tasks
    - slurm-post-tasks
    - slg.galaxy_stats
    - disable-cgroups-v2
