collections:
- ansible.posix
- community.general

roles:
- name: galaxyproject.galaxy
  version: 0.11.1
- name: galaxyproject.nginx
  version: 0.7.1
- name: galaxyproject.postgresql
  version: 1.1.7
- name: galaxyproject.postgresql_objects
  version: 1.2.0
- name: geerlingguy.pip
  version: 1.3.0
- name: geerlingguy.nfs
  version: 2.1.0
- src: usegalaxy_eu.galaxy_systemd
  version: 2.1.0
- src: usegalaxy_eu.certbot
  version: 0.1.11
#- src: jasonroyle.rabbitmq - Had to modify download URL for rabbitMQ
#  version: 0.0.4
- src: insspb.hostname
- src: galaxyproject.slurm
  version: 1.0.4
- name: galaxyproject.s3fs
  src: https://github.com/usegalaxy-au/ansible-s3fs
  version: main
- src: galaxyproject.cvmfs
  version: 0.3.0
- src: galaxyproject.repos
  version: 0.0.3
- src: galaxyproject.pulsar
  version: 1.0.11
- src: dj-wasabi.telegraf
  version: 0.14.1
- src: galaxyproject.gxadmin
  version: 0.0.12

# TIaaS roles
- src: galaxyproject.tiaas2
  version: 2.2.2
# - src: https://github.com/neoformit/ansible-tiaas2
#   name: dev-tiaas2
#   version: tiaas-3

- src: geerlingguy.docker  # TODO: test upgrading to latest version
  version: 4.1.3
- name: galaxyproject.miniconda
  version: 0.3.1
- name: usegalaxy_eu.influxdb
  version: v6.0.8
- name: cloudalchemy.grafana
  version: 0.18.0
- src: cyverse-ansible.singularity
  version: 048c4f178077d05c1e67ae8d9893809aac9ab3b7
- src: gantsign.golang
  version: 2.6.3
- name: galaxyproject.tusd
  version: 0.0.1
- name: usegalaxy_eu.flower
  version: 1.0.2
- name: usegalaxy_eu.galaxy_subdomains
  src: https://github.com/cat-bro/ansible-galaxy-subdomains
  version: make_a_variable_of_base_css_path
  # version: 0.0.13
- src: usegalaxy_eu.apptainer
  version: 0.0.1
- name: usegalaxy_eu.rabbitmqserver
  src: https://github.com/cat-bro/ansible-rabbitmq
  version: main
- name: usegalaxy_eu.walle
  src: https://github.com/usegalaxy-eu/WallE
  version: main
- name: geerlingguy.redis
  version: 1.8.0
# jenkins server roles
- name: geerlingguy.java
  version: 2.5.0
- name: geerlingguy.jenkins

# GMS roles
- name: geerlingguy.nginx
  version: 3.2.0
- name: geerlingguy.postgresql
  version: 4.0.0
