---
- name: Add functions to bashrc for managing pulsar jobs
  import_tasks: ghost_jobs_functions.yml
- name: restart munge
  systemd:
    name: munge
    state: restarted
- name: Run exportfs -ra if exportfs is available
  shell: 'if command -v exportfs >/dev/null 2>&1; then exportfs -ra; fi'
