---
- name: Disable cgroupv2
  copy:
    content: |
        GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT systemd.unified_cgroup_hierarchy=0 systemd.legacy_systemd_cgroup_controller=1"
    dest: /etc/default/grub.d/99-cgroupv1.cfg
    mode: 0644
    notify:
        - restart grub
        - reboot
