# attached_volumes
attached_volumes:
  - device: /dev/vdb
    path: /mnt
    fstype: ext4
    partition: 1

# common
hostname: "{{ ansible_hostname }}.genome.edu.au"
create_ssh_key: yes  # Only the first time.
ssl_country: "AU"
ssl_state: "Vic"
ssl_location: "Melbourne"
ssl_organisation: "Galaxy Australia"
ssl_operational_unit: "Pulsar Mel2"
ssl_email: "help@genome.edu.au"

extra_keys:
  - id: ubuntu_maintenance_key
    type: public
    from: "{{ hostvars['galaxy']['ansible_ssh_host'] }},{{ hostvars['galaxy-handlers']['ansible_ssh_host'] }},{{ hostvars['galaxy-backup']['ansible_ssh_host'] }}"

# galaxyproject.pulsar 
rabbitmq_password_galaxy_au: "{{ vault_rabbitmq_password_galaxy_mel2_prod }}"
pulsar_queue_url: "galaxy-queue.usegalaxy.org.au"
pulsar_rabbit_username: "galaxy_mel2"
pulsar_rabbit_vhost: "/pulsar/galaxy_mel2"

# geerlingguy.nfs
nfs_exports:
    - "{{ pulsar_custom_indices_dir }}  115.146.84.0/22(rw,async,no_root_squash,no_subtree_check)"
    - "/mnt/pulsar  115.146.84.0/22(rw,async,no_root_squash,no_subtree_check)"

# geerlingguy.docker
docker_daemon_options:
  data-root: /mnt/docker-data
