slurm_roles: ['exec']

add_hosts_head: yes
use_internal_ips: true

shared_mounts:
    - path: /mnt/custom-indices
      src: pulsar-nci-training:/mnt/custom-indices
      fstype: nfs
      state: mounted
    - path: /mnt/pulsar
      src: pulsar-nci-training:/mnt/pulsar
      fstype: nfs
      state: mounted
    - path: /mnt/tools-indices
      src: pulsar-nci-training:/mnt/tools-indices
      fstype: nfs
      state: absent


# cvmfs
cvmfs_cache_base: /mnt/tmpdisk/cvmfs
cvmfs_quota_limit: 20000

#Attached volume
attached_volumes:
  - device: /dev/vdc
    path: /mnt/tmpdisk
    fstype: ext4

# docker
docker_daemon_options:
  data-root: /mnt/tmpdisk/docker-data

extra_keys:
  - id: pulsar_internal_hop_key
    type: public
    from: "{{ hostvars['pulsar-nci-training']['internal_ip'] }}"
