galaxy_uid: 10010
galaxy_gid: 10010

use_internal_ips: true

# cvmfs
cvmfs_cache_base: /mnt/var/lib/cvmfs

# Use mamba as replacement for conda
pulsar_conda_exec: "mamba"

#Monitoring for Staging. Once all VM monitoring has moved to stats.usegalaxy.org.au, this can be put in all.yml and removed here.
influx_url: stats.usegalaxy.org.au
grafana_server_url: "https://{{ influx_url }}:8086"

# Monitoring
telegraf_agent_output:
  - type: influxdb
    config:
      - urls = ["{{ grafana_server_url }}"]
      - database = "pulsar-nci-training"
      - precision = "s"
      - username = "node"
      - password = "{{ vault_influx_node_password }}"

# miniconda: stop pinning conda!

# this is to override what is in all.yml with the role default
miniconda_installer: >-
  Miniconda3-{{ 'py' ~ (miniconda_python | replace('.', '')) ~ '_' ~ miniconda_version if miniconda_installer_version != 'latest' else 'latest' }}-{{ miniconda_installer_os }}-{{ miniconda_installer_arch }}.sh

miniconda_version: latest

miniconda_channels:  # defaults is no longer used in galaxy conda building
  - conda-forge
  - bioconda
miniconda_base_env_packages: []