# attached_volumes 
attached_volumes:
  - device: /dev/vdc
    path: /mnt
    fstype: ext4
    partition: 1

# common
add_hosts_head: yes
use_internal_ips: true

extra_keys:
  - id: pulsar_internal_hop_key
    type: public
    from: "{{ hostvars['pulsar-nci-training']['internal_ip'] }}"

# mounts
shared_mounts:
    - path: /mnt/custom-indices
      src: pulsar-nci-training:/mnt/custom-indices
      fstype: nfs
      state: mounted
    - path: /mnt/pulsar
      src: pulsar-nci-training:/mnt/pulsar
      fstype: nfs
      state: mounted

# galaxyproject.slurm
slurm_roles: ['exec']

# galaxyproject.cvmfs
cvmfs_cache_base: /mnt/var/lib/cvmfs
cvmfs_quota_limit: 102400

# geerlingguy.docker
docker_daemon_options:
  data-root: /mnt/docker-data
