hostname: "{{ ansible_hostname }}.usegalaxy.org.au"

attached_volumes:
  - device: /dev/vdb
    path: /mnt
    fstype: ext4
    partition: 1

# Keys and shares

create_ssh_key: yes  # Only the first time.
ssl_country: "AU"
ssl_state: "ACT"
ssl_location: "Canberra"
ssl_organisation: "Galaxy Australia"
ssl_operational_unit: "Pulsar NCI Test"
ssl_email: "help@genome.edu.au"

add_hosts_workers: yes

#host specific pulsar settings

rabbitmq_password_galaxy_au: "{{ vault_rabbitmq_password_galaxy_nci_test }}"
pulsar_queue_url: "dev-queue.gvl.org.au"
pulsar_rabbit_username: "galaxy_nci_test"
pulsar_rabbit_vhost: "/pulsar/galaxy_nci_test"

# Docker
docker_daemon_options:
  data-root: /mnt/docker-data

extra_keys:
  - id: pulsar_internal_hop_key
    type: private

# ssh config for ubuntu to ssh to worker machines
ssh_config_id_file: "/home/{{ ssh_config_user }}/.ssh/pulsar_internal_hop_key"
ssh_config_user: ubuntu
ssh_config_hosts: "{{ groups['pulsar_nci_test_workers'] }}"
