slurm_roles: ['exec']

add_hosts_head: yes
use_internal_ips: true

#Attached volume
attached_volumes:
  - device: /dev/vdb
    path: /mnt
    fstype: ext4
    partition: 1

shared_mounts:
    - path: /mnt/custom-indices
      src: pulsar-nci-test:/mnt/custom-indices
      fstype: nfs
      state: mounted
    - path: /mnt/pulsar
      src: pulsar-nci-test:/mnt/pulsar
      fstype: nfs
      state: mounted

# cvmfs
cvmfs_cache_base: /mnt/var/lib/cvmfs
cvmfs_quota_limit: 20000

# Docker
docker_daemon_options:
  data-root: /mnt/docker-data

extra_keys:
  - id: pulsar_internal_hop_key
    type: public
    from: "{{ hostvars['pulsar-nci-test']['internal_ip'] }}"