attached_volumes:
  - device: /dev/vdb
    partition: 1
    path: /mnt
    fstype: ext4

custom_indices_dir: /mnt/custom-indices

nfs_exports:
  - "{{ custom_indices_dir }} 115.146.84.0/22(rw,async,no_root_squash,no_subtree_check)"

# internal ssh key
extra_keys:
  - id: pulsar_internal_hop_key
    type: public
    from: "{{ hostvars['mel3']['ansible_ssh_host'] }}"
