# Specific settings for galaxy dev job handlers server

add_hosts_galaxy: yes
add_hosts_head: yes
add_hosts_workers: yes
add_hosts_handlers: no

attached_volumes: []

shared_mounts:
  - path: /mnt/galaxy
    src: "{{ hostvars['dev']['ansible_ssh_host'] }}:/mnt/galaxy"
    fstype: nfs
    state: mounted
  - path: /mnt/test_mount
    src: 115.146.87.37:/galaxy-backup-au
    fstype: nfs
    state: mounted
  
galaxy_config_file: /opt/galaxy/galaxy.yml

# galaxy role applied to dev-handlers machine is only needed for gravity and the galaxy config files. Skip other tasks
galaxy_manage_paths: false
galaxy_manage_clone: false
galaxy_fetch_dependencies: false
galaxy_manage_mutable_setup: false
galaxy_build_client: false

nginx_upload_job_files_store_dir: "{{ nginx_upload_store_base_dir }}/handlers_job_files"
nginx_ssl_servers:
  - galaxy-handlers

host_galaxy_config_gravity:  # overridden from entry in dev.usegalaxy.org.au
  process_manager: systemd
  galaxy_root: "{{ galaxy_server_dir }}"
  galaxy_user: "{{ galaxy_user.name }}"
  app_server: gunicorn
  virtualenv: "{{ galaxy_venv_dir }}"
  celery:
    concurrency: 2
    loglevel: DEBUG
  gunicorn:
    - bind: "unix:{{ galaxy_mutable_config_dir }}/gunicorn.handlers.sock"
      # performance options
      workers: 2
      # Other options that will be passed to gunicorn
      extra_args: '--forwarded-allow-ips="*"'
      preload: true
      environment: "{{ galaxy_process_env }}"
  handlers:
    handler:
      processes: 2
      environment: "{{ galaxy_process_env }}"
      pools:
        - job-handlers
    workflow-scheduler:
      processes: 1
      environment: "{{ galaxy_process_env }}"
      pools:
        - workflow-schedulers

# Flower
flower_python_version: python3.8
flower_app_dir: /mnt/galaxy
flower_log_file: /var/log/flower
flower_python_path: galaxy-app/lib
flower_venv_dir: /mnt/galaxy/venv
flower_app_name: galaxy.celery

flower_persistent: true

#flower_broker_api: "https://flower:{{ rabbitmq_password_flower }}@{{ rabbitmq_url }}/api/"
flower_broker_url: "amqp://flower:{{ vault_rabbitmq_password_galaxy_dev }}@dev-queue.gvl.org.au:5671//galaxy/galaxy_queues?ssl=true"

# host-specific settings for postfix
postfix_host_domain: "gvl.org.au"
postfix_hostname: "dev-handlers"
smtp_login: "{{ vault_smtp_login_dev }}"
smtp_password: "{{ vault_smtp_password_dev }}"

