# Specific settings for galaxy dev job handlers server

add_hosts_galaxy: yes
add_hosts_head: yes
add_hosts_workers: yes
add_hosts_handlers: no

add_galaxy_user: yes

attached_volumes: # TODO: check this
  - device: /dev/vdb
    path: /pvol
    fstype: ext4
    partition: 1

galaxy_mount:
  - path: /mnt/galaxy
    src: "{{ hostvars['galaxy']['internal_ip'] }}:/mnt/galaxy"
    fstype: nfs
    state: mounted

shared_mounts: "{{ galaxy_mount + galaxy_server_and_worker_shared_mounts }}"

galaxy_config_file: /opt/galaxy/galaxy.yml

# galaxy role applied to dev-handlers machine is only needed for gravity and the galaxy config files. Skip other tasks
galaxy_manage_paths: false
galaxy_manage_clone: false
galaxy_fetch_dependencies: false
galaxy_manage_mutable_setup: false
galaxy_build_client: false

galaxy_celery_tmp_dir: /pvol/celery_tmp

nginx_upload_job_files_store_dir: "{{ nginx_upload_store_base_dir }}/handlers_job_files"
nginx_ssl_servers:
  - galaxy-handlers

host_galaxy_config_gravity:
  process_manager: systemd
  galaxy_root: "{{ galaxy_server_dir }}"
  galaxy_user: "{{ galaxy_user.name }}"
  app_server: gunicorn
  virtualenv: "{{ galaxy_venv_dir }}"
  gunicorn:
    - bind: "0.0.0.0:8888"
      # performance options
      workers: 2
      # Other options that will be passed to gunicorn
      extra_args: '--forwarded-allow-ips="*"'
      preload: true
      environment: "{{ galaxy_process_env }}"
  celery: # TODO: what is this doing?
    enable: true
    enable_beat: true
    concurrency: 2
    loglevel: DEBUG
    environment:
      TMPDIR: "{{ galaxy_celery_tmp_dir }}"
  handlers:
    handler:
      environment: "{{ galaxy_process_env }}"
      processes: 5
      pools:
        - job-handlers
    workflow-scheduler:
      processes: 2
      environment: "{{ galaxy_process_env }}"
      pools:
        - workflow-schedulers

# # Flower
flower_python_version: python3
flower_app_dir: /mnt/galaxy
flower_log_file: /var/log/flower
flower_python_path: galaxy-app/lib
flower_venv_dir: /mnt/galaxy/venv
flower_app_name: galaxy.celery
flower_galaxy_conf: "{{ galaxy_config_file }}"

# flower_persistent: true

# #flower_broker_api: "https://flower:{{ rabbitmq_password_flower }}@{{ rabbitmq_url }}/api/"
flower_broker_url: "pyamqp://flower:{{ vault_rabbitmq_password_galaxy_prod }}@{{ hostvars['galaxy-queue']['internal_ip'] }}:5671//galaxy/galaxy_queues?ssl=1"

extra_keys:
  - id: internal_hop_key
    type: private
  - id: internal_hop_key
    type: public
    from: "{{ hostvars['galaxy-backup']['internal_ip'] }},{{ hostvars['galaxy']['internal_ip'] }},{{ hostvars['galaxy-queue']['internal_ip'] }}"

# override docker-data location
docker_daemon_options:
  data-root: /pvol/docker-data

# host-specific settings for postfix
postfix_host_domain: "usegalaxy.org.au"
postfix_hostname: "galaxy-handlers"
smtp_login: "{{ vault_smtp_login_prod }}"
smtp_password: "{{ vault_smtp_password_prod }}"

