---

# volume stuff
attached_volumes:
  - device: /dev/vdb
    path: /mnt
    fstype: ext4
    partition: 1

#paths
script_path: /home/ubuntu/galaxy_backup
backup_path: /mnt/galaxy-backups

#swift for backups
use_swift: true

swift_backup_container: 'usegalaxy-au-db'
swift_cred_file: "{{ script_path }}/GenomicsVL-openrc.sh"  # IMPORTANT: this file needs to be added by a user with credentials
venv_location: "{{ script_path }}/venv"

#slack integration
use_slack: true
slack_galaxy_log_webhook: "{{ vault_slack_galaxy_log_webhook }}"

#The name of the database to backup
psql_db: 'galaxy'

#Database connection vars
db_user: galaxy
db_password: "{{ vault_galaxy_db_user_password }}"
db_server: "{{ hostvars['galaxy-db']['internal_ip'] }}"
db_port: 5432

# Retention time variables
monthly_backup_day: 1  #Monthly backups will run on this day of the month
weekly_backup_day: 6  #Weekly backups will run on this day of the week
retention_day: 6       #Keep daily backups for this many days (6 days)
retention_week: 21     #Keep weekly backups for this many days (21 days = 3 weeks)
retention_month: 61    #Keep monthly backups for this many days (61 days ~ 2 months)

extra_keys:
  - id: internal_hop_key
    type: private
  - id: internal_hop_key
    type: public
    from: "{{ hostvars['galaxy']['internal_ip'] }},{{ hostvars['galaxy-queue']['internal_ip'] }},{{ hostvars['galaxy-handlers']['internal_ip'] }}"

# ssh config, only for ubuntu
ssh_config_id_file: "/home/{{ ssh_config_user }}/.ssh/internal_hop_key"
ssh_config_user: ubuntu
ssh_config_hosts: "{{ groups['galaxy_group'] }}"

# Extra users who can access db backups
host_machine_users:
    - name: uwe
      uid: 7400
      roles: []
      key: files/keys/uwe.pub
      email: "{{ uwe_email }}"
    - name: jonathan
      uid: 7401
      roles: []
      key: files/keys/jonathan.pub
      email: "{{ jonathan_email }}"
