volA_path: /mnt/volA
volB_path: /mnt/volB
volC_path: /mnt/volC
volD_path: /mnt/volD

# volume A (~171 TB)
nfs_data25_dir: "{{ volA_path }}/data25"
nfs_data26_dir: "{{ volA_path }}/data26"
nfs_data27_dir: "{{ volA_path }}/data27"
nfs_data28_dir: "{{ volA_path }}/data28"
nfs_data29_dir: "{{ volA_path }}/data29"
nfs_data30_dir: "{{ volA_path }}/data30"
nfs_data33_dir: "{{ volA_path }}/data33"

# volume B (~49 TB)
# data folders moved to QLD, September 2025 (data08, data09, data12, data15, data17, data20)
nfs_data22_dir: "{{ volB_path }}/data22"  # moved from volA June '25
nfs_data35_dir: "{{ volB_path }}/data35"

# volume C (~37 TB)
# data folders moved to QLD, September 2025 (data10, data11, data13, data16, data18, data21)

# volume D (~107 TB)
# data folder data14 moved to QLD, September 2025
nfs_data19_dir: "{{ volD_path }}/data19"  # moved from volA April '25
nfs_data23_dir: "{{ volD_path }}/data23"
nfs_data24_dir: "{{ volD_path }}/data24"
nfs_data31_dir: "{{ volD_path }}/data31"
nfs_data32_dir: "{{ volD_path }}/data32"
nfs_data34_dir: "{{ volD_path }}/data34"

attached_volumes:
  - device: /dev/vdb
    partition: 1
    path: "{{ volA_path }}"
    fstype: ext4
  - device: /dev/vdc
    partition: 1
    path: "{{ volB_path }}"
    fstype: ext4
  - device: /dev/vdd
    partition: 1
    path: "{{ volC_path }}"
    fstype: ext4
  - device: /dev/vde
    partition: 1
    path: "{{ volD_path }}"
    fstype: ext4

nfs_dirs:
  - "{{ nfs_data19_dir }}"
  - "{{ nfs_data22_dir }}"
  - "{{ nfs_data23_dir }}"
  - "{{ nfs_data24_dir }}"
  - "{{ nfs_data25_dir }}"
  - "{{ nfs_data26_dir }}"
  - "{{ nfs_data27_dir }}"
  - "{{ nfs_data28_dir }}"
  - "{{ nfs_data29_dir }}"
  - "{{ nfs_data30_dir }}"
  - "{{ nfs_data31_dir }}"
  - "{{ nfs_data32_dir }}"
  - "{{ nfs_data33_dir }}"
  - "{{ nfs_data34_dir }}"
  - "{{ nfs_data35_dir }}"

nfs_exports:
  - "{{ volA_path }} {{ hostvars['galaxy'].internal_ip.split('.')[:-1] | join('.') }}.0/24(rw,async,no_root_squash,no_subtree_check)"
  - "{{ volB_path }} {{ hostvars['galaxy'].internal_ip.split('.')[:-1] | join('.') }}.0/24(rw,async,no_root_squash,no_subtree_check)"
  - "{{ volC_path }} {{ hostvars['galaxy'].internal_ip.split('.')[:-1] | join('.') }}.0/24(rw,async,no_root_squash,no_subtree_check)"
  - "{{ volD_path }} {{ hostvars['galaxy'].internal_ip.split('.')[:-1] | join('.') }}.0/24(rw,async,no_root_squash,no_subtree_check)"

# internal ssh keys
extra_keys:
  - id: internal_hop_key
    type: public
    from: "{{ hostvars['galaxy']['internal_ip'] }},{{ hostvars['galaxy-backup']['internal_ip'] }},{{ hostvars['galaxy-queue']['internal_ip'] }},{{ hostvars['galaxy-handlers']['internal_ip'] }}"
