postgresql_flavor: pgdg
postgresql_version: 14

attached_volumes:
  - device: /dev/vdb # TODO: check mount point
    path: /data
    partition: 1
    fstype: ext4

postgresql_conf:
  # Postgresql settings from: https://pgtune.leopard.in.ua/#/ - recommended by @natefoo.
  # Inout settings:
  #   DB Version: 12
  #   OS Type: linux
  #   DB Type: web
  #   Total Memory (RAM): 32 GB # TODO: update settings for 64GB RAM
  #   CPUs num: 8
  #   Connections num: 100
  #   Data Storage: san
  - max_connections: 300
  - listen_addresses: "'*'"   # Allow remote connections
  - data_directory: "'/data/production'"
  - shared_buffers: 16GB
  - effective_cache_size: 32GB
  - maintenance_work_mem : 3GB
  - checkpoint_completion_target: 0.7
  - wal_buffers: 16MB
  - default_statistics_target: 100
  - random_page_cost: 4
  - effective_io_concurrency: 2
  - work_mem: 54MB
  - min_wal_size: 1GB
  - max_wal_size: 4GB
  - max_worker_processes: 8
  - max_parallel_workers_per_gather: 4
  - max_parallel_workers: 8
  - max_parallel_maintenance_workers: 4
  - temp_buffers: 64MB
  # - log_filename: "'postgresql-%Y-%m-%d.log'"
  # - log_statement: all
  # - logging_collector: on  # altering this requires a restart
  - wal_level: replica
  - max_wal_senders: 5
  - wal_keep_size: 1GB

postgresql_pgdata: "/data/production"

postgresql_pg_hba_conf:
  - host all all "{{ hostvars['galaxy']['internal_ip'] }}/32" md5
  - host all all "{{ hostvars['galaxy-handlers']['internal_ip'] }}/32" md5
  - host all all "{{ hostvars['galaxy-backup']['internal_ip'] }}/32" md5
  - host replication replicator "{{ hostvars['replicant-galaxy-db']['ansible_ssh_host'] }}/32" md5

extra_keys:
  - id: internal_hop_key
    type: public
    from: "{{ hostvars['galaxy']['internal_ip'] }},{{ hostvars['galaxy-backup']['internal_ip'] }},{{ hostvars['galaxy-handlers']['internal_ip'] }},{{ hostvars['galaxy-queue']['internal_ip'] }}"

host_postgresql_objects_users:
  - name: replicator
    password: "{{ vault_galaxy_db_replicator_password }}"
    role_attr_flags: "REPLICATION,LOGIN"
    db: galaxy
