- name: Find default webhooks dirs on the host
  find:
    paths: "{{ webhook_plugins_builtin_dir }}"
    patterns: "*"
    types: "d"  # Only directories
  register: found_dirs

- name: copy default webhooks to plugins directory
  copy:
    src: "{{ item.path }}"
    dest: "{{ webhook_plugins_dest_dir }}/{{ item.name }}"
    owner: galaxy
    group: galaxy
    mode: '0755'
    remote_src: yes
  loop: "{{ found_dirs.files }}"
