# Copy local webhooks into webhooks folder
- name: ensure webhook plugins destination directory exists
  file:
    path: "{{ webhook_plugins_dest_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: copy default webhooks to Galaxy plugins directory
  include_tasks: copy_builtin_webhooks.yml

- name: copy webhooks to Galaxy plugins directory
  include_tasks: copy_webhooks.yml
  loop: "{{ webhook_plugins }}"
  loop_control:
    loop_var: webhook_name

- name: collect existing webhook directories
  shell: ls -1 {{ webhook_plugins_dest_dir }}
  register: existing_webhook_plugin_dirs

- name: remove unwanted webhook directories
  file:
    path: "{{ webhook_plugins_dest_dir }}/{{ item }}"
    state: absent
  with_items: "{{ existing_webhook_plugin_dirs.stdout_lines }}"
  when: "item not in webhook_plugins"
