# attached_volumes 
attached_volumes:
  - device: /dev/vdb
    path: /mnt
    fstype: ext4
    partition: 1

# common
add_hosts_head: yes

# mounts
shared_mounts:
    - path: /mnt/custom-indices
      src: pulsar-mel2:/mnt/custom-indices
      fstype: nfs
      state: mounted
    - path: /mnt/pulsar
      src: pulsar-mel2:/mnt/pulsar
      fstype: nfs
      state: mounted

# galaxyproject.slurm
slurm_roles: ['exec']

# galaxyproject.cvmfs
cvmfs_cache_base: /mnt/var/lib/cvmfs
cvmfs_quota_limit: 20000

# geerlingguy.docker
docker_daemon_options:
  data-root: /mnt/docker-data
