- name: update labs cache
  ansible.builtin.command: >
    docker compose --profile prod run --rm labs-engine
    python manage.py update_cache
  args:
    chdir: "{{ labs_config_root }}"
  tags:
    - always
