slurm_roles: ['exec']

add_hosts_head: yes

shared_mounts:
    - path: /mnt/custom-indices
      src: "{{ hostvars['pulsar-mel3-nfs']['ansible_ssh_host'] }}:/mnt/custom-indices"
      fstype: nfs
      state: mounted
    - path: /mnt/pulsar
      src: pulsar-mel3:/mnt/pulsar
      fstype: nfs
      state: mounted

# cvmfs
cvmfs_cache_base: /mnt/var/lib/cvmfs
cvmfs_quota_limit: 20000

#Attached volume
attached_volumes:
  - device: /dev/vdb
    path: /mnt
    fstype: ext4
    partition: 1

# docker
docker_daemon_options:
  data-root: /mnt/docker-data

# internal ssh key
extra_keys:
  - id: pulsar_internal_hop_key
    type: public
    from: "{{ hostvars['pulsar-mel3']['ansible_ssh_host'] }}"
