slurm_roles: ['exec']

add_hosts_head: yes

shared_mounts:
    - path: /mnt/custom-indices
      src: "{{ hostvars['pulsar-QLD-nfs']['ansible_ssh_host'] }}:/mnt/custom-indices"
      fstype: nfs
      state: mounted
    - path: /mnt/pulsar
      src: pulsar-QLD:/mnt/pulsar
      fstype: nfs
      state: mounted


# cvmfs
cvmfs_cache_base: /mnt/var/lib/cvmfs
cvmfs_quota_limit: 102400

#Attached volume
attached_volumes:
  - device: /dev/vdb
    partition: 1
    path: /mnt
    fstype: ext4